name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  autoformat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app # Garante que o npm ci rode na pasta correta
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: |
          npm ci
          npx prettier . --write
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"

  build-and-test:
    name: Build & Test
    needs: autoformat
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "${{ github.workspace }}/app/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Approve Allow-Scripts
        run: npx @lavamoat/allow-scripts auto

      - name: Type check
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test --if-present
